package tysheng.sxbus.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import tysheng.sxbus.bean.Star;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig starDaoConfig;

    private final StarDao starDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        starDaoConfig = daoConfigMap.get(StarDao.class).clone();
        starDaoConfig.initIdentityScope(type);

        starDao = new StarDao(starDaoConfig, this);

        registerDao(Star.class, starDao);
    }

    public void clear() {
        starDaoConfig.clearIdentityScope();
    }

    public StarDao getStarDao() {
        return starDao;
    }

}
